import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-20">
      <article className="prose prose-invert max-w-none">
        <h1>Terms of Service</h1>
        <p>Last updated: July 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using SafeSetu (&ldquo;the Service&rdquo;), you agree
          to be bound by these Terms of Service. If you do not agree, do not use
          the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          SafeSetu is a security scanning platform that analyzes code
          repositories for common vulnerabilities. The Service reads your code
          via the GitHub API, runs automated security checks, and provides
          findings with suggested fixes.
        </p>

        <h2>3. User Responsibilities</h2>
        <ul>
          <li>You must have authorization to scan any repository you connect.</li>
          <li>
            You are responsible for maintaining the security of your account
            credentials.
          </li>
          <li>
            You agree not to use the Service for any unlawful purpose or to
            violate any regulations.
          </li>
          <li>
            You acknowledge that scan results are advisory and do not constitute
            a guarantee of security.
          </li>
        </ul>

        <h2>4. Intellectual Property</h2>
        <p>
          SafeSetu does not claim ownership of your code or repositories. Scan
          results generated by the Service are provided for your use. The
          Service itself, including its design, algorithms, and branding, remains
          the intellectual property of SafeSetu.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranty of any
          kind. SafeSetu shall not be liable for any indirect, incidental, or
          consequential damages arising from your use of the Service. Scan
          results do not guarantee the absence of vulnerabilities.
        </p>

        <h2>6. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the
          Service at any time for violation of these terms. You may delete your
          account at any time through your account settings.
        </p>

        <h2>7. Governing Law</h2>
        <p>
          These terms are governed by and construed in accordance with applicable
          law. Any disputes shall be resolved in the appropriate jurisdiction.
        </p>
      </article>
    </div>
  );
}
