import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-20">
      <article className="prose prose-invert max-w-none">
        <h1>Privacy Policy</h1>
        <p>Last updated: July 2026</p>

        <h2>1. Data We Collect</h2>
        <ul>
          <li>
            <strong>GitHub account information:</strong> username, email address,
            and profile avatar via GitHub OAuth.
          </li>
          <li>
            <strong>GitHub access token:</strong> used exclusively to read
            repository contents during scans.
          </li>
          <li>
            <strong>Scan results:</strong> findings, severity ratings, and
            security scores generated by our analysis.
          </li>
        </ul>

        <h2>2. How We Use Your Data</h2>
        <p>
          We use collected data solely to provide the SafeSetu service: scanning
          your repositories for security vulnerabilities, generating findings,
          and displaying results in your dashboard.
        </p>

        <h2>3. Data Storage</h2>
        <p>
          All data is encrypted at rest. Access tokens are stored encrypted and
          are only decrypted during active scans. Your source code is never
          stored — it is read via the GitHub API during a scan and discarded
          immediately after analysis.
        </p>

        <h2>4. Third-Party Sharing</h2>
        <p>
          We do not sell, rent, or share your personal data or scan results with
          third parties. We do not use your data for advertising or marketing
          purposes.
        </p>

        <h2>5. Data Retention</h2>
        <p>
          Scan results and account data are retained until you delete your
          account. Upon account deletion, all associated data is permanently
          removed from our systems.
        </p>

        <h2>6. Your Rights</h2>
        <p>
          You may delete your account and all associated data at any time from
          your account settings. Account deletion is immediate and irreversible —
          all scan history, connected repositories, and personal information will
          be permanently erased.
        </p>

        <h2>7. Cookies</h2>
        <p>
          SafeSetu uses session cookies only, required for authentication. We do
          not use tracking cookies, analytics cookies, or any third-party cookie
          services.
        </p>

        <h2>8. Contact</h2>
        <p>
          For privacy-related inquiries, reach out via the contact information on
          our GitHub repository.
        </p>
      </article>
    </div>
  );
}
